class Reciters {
  String name;
  String server;
  int no;
  Reciters(this.name, this.server, this.no);

  static List<Reciters> listofReciters = [
    Reciters('Abdelbari Al-Toubayti', '6:thubti', 0),
    Reciters('Abdul Aziz Al-Ahmad', '11:a_ahmed', 1),
    Reciters('Abdulaziz Az-Zahrani', '9:zahrani', 2),
    Reciters('Abdulbari Mohammad', '12:bari', 3),
    Reciters('Abdulbasit Abdulsamad I', '7:basit', 4),
    Reciters('Abdulbasit Abdulsamad II', '10:basit_warsh', 5),
    Reciters('Abdulbasit Abdulsamad III', '13:basit_mjwd', 6),
    Reciters('Abdulhadi Kanakeri', '6:kanakeri', 7),
    Reciters('Abdullah Al-Johany', '13:jhn', 8),
    Reciters('Abdullah Al-Kandari', '10:Abdullahk', 9),
    Reciters('Abdullah Al-Khalaf', '14:khalf', 10),
    Reciters('Abdullah Al-Mattrod', '8:mtrod', 11),
    Reciters('Abdullah Basfer', '6:bsfr', 12),
    Reciters('Abdullah Kamel', '16:kamel/Rewayat-Hafs-A-n-Assem', 13),
    Reciters('Abdullah Khayyat', '12:kyat', 14),
    Reciters('Abdullah Qaulan', '8:gulan/Rewayat-Hafs-A-n-Assem', 15),
    Reciters('Abdulmohsen Al-Qasim', '8:qasm', 16),
    Reciters('Abdulmohsin Al-Harthy', '6:mohsin_harthi', 17),
    Reciters('Abdulmohsin Al-Obaikan', '12:obk', 18),
    Reciters('Abdulrahman Al-Majed', '10:a_majed',
        19), //previously it was "10/a_majed"
    Reciters('Abdulrahman Aloosi', '6:aloosi', 20),
    Reciters('Abdulrahman Alsudaes', '11:sds', 21),
    Reciters('Abdulrasheed Soufi I', '16:soufi-hfs/Rewayat-Hafs-A-n-Assem', 22),
    Reciters('Abdulrasheed Soufi II', '9:soufi', 23),
    Reciters('Abdulrasheed Soufi III', '9:soufi_klf', 24),
    Reciters('Abdulwadood Haneef', '8:wdod', 25),
    Reciters('Addokali Mohammad Alalim', '7:dokali', 26),
    Reciters('Adel Al-Khalbany', '8:a_klb', 27),
    Reciters('Adel Ryyan', '8:ryan', 28),
    Reciters('Ahmad Al-Ajmy', '10:ajm/128', 29),
    Reciters('Ahmad Al-Hawashi', '11:hawashi', 30),
    Reciters('Ahmad Deban', '16:deban/Rewayat-Hafs-A-n-Assem', 31),
    Reciters('Ahmad Khader Al-Tarabulsi', '10:trablsi', 32),
    Reciters('Ahmad Nauina', '11:ahmad_nu', 33),
    Reciters('Ahmad Saber', '8:saber', 34),
    Reciters('Ahmed Al-Swailem', '14:swlim/Rewayat-Hafs-A-n-Assem', 35),
    Reciters('Ahmed Al-trabulsi', '10:trabulsi', 36),
    Reciters('Ahmed Amer', '10:Aamer', 37),
    Reciters('Akram Alalaqmi', '9:akrm', 38),
    Reciters('Al-Qaria Yassen', '11:qari', 39),
    Reciters('Alashri Omran', '9:omran', 40),
    Reciters('Alfateh Alzubair', '6:fateh', 41),
    Reciters('Ali Alhuthaifi', '9:huthifi_qalon', 42),
    Reciters('Ali Alhuthaifi', '9:hthfi', 43),
    Reciters('Ali Hajjaj Alsouasi', '9:hajjaj', 44),
    Reciters('Ali Jaber', '11:a_jbr', 45),
    Reciters('Aloyoon Al-Koshi', '11:koshi', 46),
    Reciters('Alzain Mohammad Ahmad', '9:alzain', 47),
    Reciters('Bader Alturki', '10:bader/Rewayat-Hafs-A-n-Assem', 48),
    Reciters('Bandar Balilah', '6:balilah', 49),
    Reciters('Emad Hafez', '6:hafz', 50),
    Reciters('Fares Abbad', '8:frs_a', 51),
    Reciters('Hani Arrifai', '7:hani', 52),
    Reciters('Hatem Fareed Alwaer', '11:hatem', 53),
    Reciters('Ibrahim Al-Akdar', '6:akdr', 54),
    Reciters('Ibrahim Aldosari I', '10:ibrahim_dosri_warsh', 55),
    Reciters('Ibrahim Aldosari II', '10:ibrahim_dosri_hafs', 56),
    Reciters(
        'Ibrahim Aljormy', '11:jormy/Rewayat-Hafs-A-n-Assem', 57), //check??
    Reciters('Jamaan Alosaimi', '6:jaman', 58),
    Reciters('Jamal Shaker Abdullah', '6:jamal', 59),
    Reciters('Khaled Al-Qahtani', '10:qht', 60),
    Reciters('Khalid Abdulkafi', '11:kafi', 61),
    Reciters('Khalid Al-Jileel', '10:jleel', 62),
    Reciters('Khalid Almohana', '11:mohna', 63),
    Reciters('Khalifa Altunaiji', '12:tnjy', 64),
    Reciters('Maher Al Meaqli', '12:maher', 65),
    Reciters('Maher Shakhashero', '10:shaksh', 66),
    Reciters('Mahmood Al rifai', '11:mrifai', 67),
    Reciters('Mahmood AlSheimy', '10:sheimy', 68),
    Reciters('Mahmoud Ali  Albanna', '8:bna_mjwd', 69),
    Reciters('Mahmoud Ali  Albanna', '8:bna', 70),
    Reciters(
        'Mahmoud Khalil Al-Hussary I', '13:husr/Rewayat-Qalon-A-n-Nafi', 71),
    Reciters('Mahmoud Khalil Al-Hussary II',
        '13:husr/Rewayat-Aldori-A-n-Abi-Amr', 72),
    Reciters('Mahmoud Khalil Al-Hussary III', '9:husr_warsh', 73),
    Reciters('Mahmoud Khalil Al-Hussary IV', '9:husr_mjwd', 74),
    Reciters('Mahmoud Khalil Al-Hussary V', '13:husr', 75),
    Reciters('Majed Al-Zamil', '9:zaml', 76),
    Reciters('Mishary Alafasi', '8:afs', 77),
    Reciters('Moeedh Alharthi', '8:harthi', 78),
    Reciters('Mohammad Abdullkarem I', '12:m_krm', 79),
    Reciters('Mohammad Abdullkarem II', '7:m_kreem_warsh', 80),
    Reciters('Mohammad Al-Abdullah I', '12:abdullah_dori', 81),
    Reciters('Mohammad Al-Abdullah II', '9:abdullah', 82),
    Reciters('Mohammad Al-Airawy',
        '6:earawi/Rewayat-Warsh-A-n-Nafi-Men-Tariq-Abi-Baker-Alasbahani', 83),
    Reciters('Mohammad Al-Tablaway', '12:tblawi', 84),
    Reciters('Mohammad Rashad Alshareef', '10:rashad', 85),
    Reciters('Mohammad Saleh Alim Shah', '12:shah', 86),
    Reciters('Mohammed Al-Lohaidan', '8:lhdan', 87),
    Reciters('Mohammed Al-Muhasny', '11:mhsny', 88),
    Reciters('Mohammed Ayyub', '8:ayyub', 89),
    Reciters('Mohammed Jibreel', '8:jbrl', 90),
    Reciters('Mohammed Osman Khan', '6:khan', 91),
    Reciters('Mohammed Siddiq Al-Minshawi', '11:minsh_mjwd', 92),
    Reciters('Mohammed Siddiq Al-Minshawi', '10:minsh', 93),
    Reciters('Mousa Bilal', '11:bilal', 94),
    Reciters('Muftah Alsaltany I', '11:muftah_thakwan', 95),
    Reciters('Muftah Alsaltany II', '9:sultany', 96),
    Reciters('Muftah Alsaltany III', '10:muftah', 97),
    Reciters('Muftah Alsaltany IV', '6:saltany_kisaia', 98),
    Reciters('Mustafa Al-Lahoni', '6:lahoni', 99),
    Reciters('Mustafa Ismail', '8:mustafa', 100),
    Reciters('Mustafa raad Alazawy', '8:ra3ad', 101),
    Reciters('Nabil Al Rifay', '9:nabil', 102),
    Reciters('Nasser Almajed', '14:nasser_almajed', 103),
    Reciters('Nasser Alqatami', '6:qtm', 104),
    Reciters('Nathier Almalki', '16:nathier/Rewayat-Hafs-A-n-Assem', 105),
    Reciters('Neamah Al-Hassan', '8:namh', 106),
    Reciters('Omar Al-Qazabri', '9:omar_warsh', 107),
    Reciters('Rachid Belalya', '6:bl3/Rewayat-Warsh-A-n-Nafi', 108),
    Reciters('Rami Aldeais', '6:rami', 109),
    Reciters('Saad Al-Ghamdi', '7:s_gmd', 110),
    Reciters('Saad Almqren', '16:saad/Rewayat-Hafs-A-n-Assem', 111), //check???
    Reciters('Saber Abdulhakm', '12:hkm', 112),
    Reciters('Sahl Yassin', '6:shl', 113),
    Reciters('Salah Albudair', '6:s_bud', 114),
    Reciters('Salah Alhashim', '12:salah_hashim_m', 115),
    Reciters('Saleh Al-Habdan', '6:habdan/Rewayat-Hafs-A-n-Assem', 116),
    Reciters('Saud Al-Shuraim', '7:shur', 117),
    Reciters('Sayeed Ramadan', '12:sayed', 118),
    Reciters('Shaik Abu Bakr Al Shatri', '11:shatri', 119),
    Reciters('Shirazad Taher', '12:taher', 120),
    Reciters('Slaah Bukhatir', '8:bu_khtr', 121),
    Reciters('Tareq Abdulgani daawob', '10:tareq', 122),
    Reciters('Tawfeeq As-Sayegh', '6:twfeeq', 123),
    Reciters('Wadeea Al-Yamani', '6:wdee3', 124),
    Reciters('Waleed Alnaehi', '9:waleed', 125),
    Reciters('Yahya Hawwa', '12:yahya', 126),
    Reciters('Yasser Al-Dosari', '11:yasser', 127),
    Reciters('Yasser Al-Mazroyee', '9:mzroyee', 128),
    Reciters('Yasser Al-Qurashi', '9:qurashi', 129),
    Reciters(
        'Yasser Salamah', '12:salamah/Rewayat-Hafs-A-n-Assem', 130), //check??
    Reciters('Yousef Alshoaey', '9:yousef', 131),
    Reciters('Yousef Bin Noah Ahmad', '8:noah', 132),
    Reciters('Zaki Daghistani', '9:zaki', 133),
  ];
}
